### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by peterhellberg** [mehlon/imagefile#5]
Is this project licensed under the ISC-License, like [imagefile](http://git.2f30.org/imagefile/tree/LICENSE) is?

**Comment by mehlon** [comment]
I have just added a license: it is public domain.

**Comment by peterhellberg** [comment]
Thank you :+1: 

I’d like to help out with some tests and a small addition to make Imagefile implement the draw.Image interface. Should I open separate PR's for this?

**Comment by mehlon** [comment]
Yeah, that's OK.
