### ISSUE TITLE
Panic in At method on Imagefile

### ISSUE THREAD

**Issue by peterhellberg** [mehlon/imagefile#7]
The `At` method doesn’t check if x and y are out of bounds:

```go
package main

import "github.com/mehlon/imagefile"

func main() {
	m := imagefile.Imagefile{}
	m.At(1, 2) // This will panic: runtime error: index out of range
}
```

**Comment by mehlon** [comment]
I wonder if we can just use https://golang.org/pkg/image/#RGBA ?

https://github.com/mehlon/imagefile/issues/8

**Comment by peterhellberg** [comment]
Yes, but a quick fix is to check if x and y is inside of bounds (calculated from Width and Height)
