### ISSUE TITLE
Use image/RGBA

### ISSUE THREAD

**Issue by mehlon** [mehlon/imagefile#8]
https://golang.org/pkg/image/#RGBA
This would allow us to remove some code.

**Comment by peterhellberg** [comment]
I could give it a shot to replace the Buf with a image.RGBA if you want?

**Comment by mehlon** [comment]
I was actually rather thinking to remove the `Imagefile` struct altogether from the code and either using RGBA.Set() or reading directly into RGBA.Pix

**Comment by peterhellberg** [comment]
Ok, then you’ll probably need separate variables for the (uint32) width and height?

Once you have decoded width and height you could just `m := image.NewRGBA(image.Rect(0, 0, int(w), int(h)))` and `m.Set(x,y,color.RGBA{rgba[0], rgba[1], rgba[2], rgba[3]})`

**Comment by peterhellberg** [comment]
Are you working on this change or is it up for grabs?

**Comment by mehlon** [comment]
I currently don't have access to a coding environment, so go ahead.

**Comment by peterhellberg** [comment]
Ok :+1:

**Comment by peterhellberg** [comment]
Almost done with the change now
